[build-system]
# Tells Python how to build the package.
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "beamfomig-python" # The name your package will have.
version = "0.1.0" # The initial version.
description = "Proyecto de Beamforming en Python"
readme = "README.md"
authors = [{name = "Tu Nombre", email = "tu.email@ejemplo.com"}]
license = {file = "LICENSE"} # If you have a license file.
keywords = ["beamforming", "mems", "array", "audio"]

# Your project's dependencies. Make sure to include the libraries you use.
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pyroomacoustics",
    "h5py",
    "streamlit",
    "plotly",
    "pandas",
    "tqdm",
    "tensorflow",
    "mir_eval",
    "pysepm",
    "numba",
    "pb_bss"
]

[tool.setuptools.packages]
# This section is CRUCIAL. It indicates where the modules are located.
# In your case, 'src' contains the 'beamforming' and 'propagation' packages.
# The following line tells setuptools to look for packages inside the 'src' folder.
find = {where = ["src"]}