import numpy as np
import scipy.signal as signal
import torch
from asteroid.models import ConvTasNet
import os

from propagation.simulate_acoustics import SimAcoustic
from utils.audio import save_wav, normalize_signal
from dereverberation.nara_wrappers import process_wpe_online
from beamforming.signal_model import compute_rtf_steering_vector

def extract_neural_masks(mic_0_audio, fs, model_name, length_fft=512, hop_length_fft=256):
    """
    Passes Mic 0 audio through ConvTasNet (sepclean) and generates TWO masks and raw audios.
    """
    print(f" -> [Neural Network] Loading Separation model: {model_name}...")
    model = ConvTasNet.from_pretrained(model_name)
    model.eval()

    # PyTorch expects tensors of shape [Batch, Channels, Time]
    input_tensor = torch.tensor(mic_0_audio, dtype=torch.float32).unsqueeze(0).unsqueeze(0)

    print(" -> [Neural Network] Processing audio (Inference)...")
    with torch.no_grad():
        est_sources = model(input_tensor) # Shape: [1, 2, Time]

    # Extract both separated raw audios
    audio_1 = est_sources[0, 0, :].numpy()
    audio_2 = est_sources[0, 1, :].numpy()

    # Compute STFTs to calculate masks
    print(" -> [Neural Network] Computing masks in the frequency domain...")
    _, _, Zxx_mix = signal.stft(mic_0_audio, fs=fs, nperseg=length_fft, noverlap=length_fft - hop_length_fft)
    _, _, Zxx_1 = signal.stft(audio_1, fs=fs, nperseg=length_fft, noverlap=length_fft - hop_length_fft)
    _, _, Zxx_2 = signal.stft(audio_2, fs=fs, nperseg=length_fft, noverlap=length_fft - hop_length_fft)

    mag_mix = np.abs(Zxx_mix)
    
    # Calculate ratio masks for both sources and apply clipping
    M_1 = np.abs(Zxx_1) / (mag_mix + 1e-8)
    M_2 = np.abs(Zxx_2) / (mag_mix + 1e-8)
    
    M_1 = np.clip(M_1, 0.05, 0.95)
    M_2 = np.clip(M_2, 0.05, 0.95)

    return M_1, M_2, audio_1, audio_2

def spatial_permutation_judge(X_stft, M_1, M_2, sv, audio_1, audio_2):
    """
    Resolves the permutation problem by projecting the target steering vector
    onto the spatial covariance matrices generated by each mask.
    Returns the winning mask, the noise mask, and the winning raw audio.
    """
    print(" -> [Spatial Judge] Evaluating spatial covariances...")
    K, T, M = X_stft.shape
    
    score_1 = 0.0
    score_2 = 0.0
    
    # Evaluate spatial alignment for each frequency bin
    for f in range(K):
        X_f = X_stft[f, :, :] # Shape: (T, M)
        v = sv[f, :].reshape(M, 1) # Steering vector for frequency f
        
        # Weighted spatial covariance for Mask 1
        R_1 = np.einsum('t,tm,tn->mn', M_1[f, :], X_f, X_f.conj())
        tr_R1 = np.real(np.trace(R_1)) + 1e-10
        # Normalized spatial power in direction v
        p_1 = np.real(v.conj().T @ R_1 @ v) / tr_R1
        score_1 += p_1[0, 0]
        
        # Weighted spatial covariance for Mask 2
        R_2 = np.einsum('t,tm,tn->mn', M_2[f, :], X_f, X_f.conj())
        tr_R2 = np.real(np.trace(R_2)) + 1e-10
        p_2 = np.real(v.conj().T @ R_2 @ v) / tr_R2
        score_2 += p_2[0, 0]

    # Determine the winner based on spatial alignment score
    if score_1 > score_2:
        print(f" -> [Spatial Judge] Mask 1 matches target angle! (Score: {score_1:.2f} vs {score_2:.2f})")
        return M_1, M_2, audio_1 
    else:
        print(f" -> [Spatial Judge] Mask 2 matches target angle! (Score: {score_2:.2f} vs {score_1:.2f})")
        return M_2, M_1, audio_2 

def Neural_MVDR_recursive(X_stft, M_target, fs, array_geometry, source_pos, beta=1e-3, min_loading=1e-6):
    """
    Exact MVDR algorithm, but guided by the neural mask instead of analytical SPP.
    """
    lamda = 0.99
    K, T, M = X_stft.shape  
    frecs = np.linspace(0, fs/2, K)

    sv = compute_rtf_steering_vector(frecs, source_pos, array_geometry, ref_mic_idx=0, mode="near_field", squeeze=True)
    
    Y_stft = np.zeros((K, T), dtype=np.complex128)
    R_nn = np.tile(np.eye(M, dtype=np.complex128) * 1e-6, (K, 1, 1))
    
    phi_s = 1e-3 
    R_ss_init = phi_s * np.einsum("fm,fn->fmn", sv, sv.conj())
    R_xx = R_ss_init + R_nn

    initial_diag_load = np.tile(np.eye(M, dtype=np.complex128) * min_loading, (K, 1, 1))
    R_nn_inv = np.linalg.inv(R_nn + initial_diag_load)

    for m in range(T):
        X_frame = X_stft[:, m, :]

        # Replace SPP calculation with the neural mask value for this frame
        P_expand = M_target[:, m, np.newaxis, np.newaxis]

        # Update Covariance Matrices
        R_instant = np.einsum("fm,fn->fmn", X_frame, X_frame.conj())
        R_xx = lamda * R_xx + (1 - lamda) * P_expand * R_instant
        R_nn = lamda * R_nn + (1 - lamda) * (1 - P_expand) * R_instant

        # Compute dynamic diagonal loading
        tr_R = np.real(np.trace(R_nn, axis1=1, axis2=2))
        adaptive_load = beta * (tr_R[:, None, None] / M)
        loading = np.maximum(adaptive_load, min_loading)
        R_nn_stable = R_nn + np.eye(M)[None, :, :] * loading
        R_nn_inv = np.linalg.inv(R_nn_stable)

        # Calculate MVDR weights
        weights_nom = np.einsum("fmn,fn->fm", R_nn_inv, sv)
        weights_den = np.einsum("fm,fm->f", sv.conj(), weights_nom)
        weights = weights_nom / (weights_den[:, np.newaxis] + 1e-10)
        
        # Apply weights
        Y_stft[:, m] = np.einsum("fm,fm->f", weights.conj(), X_frame)

    return Y_stft

def apply_neural_mvdr_bridge(time_domain_input, mic_coords, source_pos_2d, fs, model_name, length_fft=512, hop_length_fft=256):
    """
    The complete pipeline: WAV -> Neural Masks -> Spatial Judge -> MVDR -> WAV
    """
    mic_0_audio = time_domain_input[0, :]
    
    # 1. Extract BOTH masks and raw audios from the network
    M_1, M_2, raw_1, raw_2 = extract_neural_masks(mic_0_audio, fs, model_name, length_fft, hop_length_fft)
    
    # 2. Compute STFT of all channels
    freqs, times, Zxx = signal.stft(
        time_domain_input, fs=fs, nperseg=length_fft, noverlap=length_fft - hop_length_fft
    )
    X_stft = np.transpose(Zxx, (1, 2, 0)) # Shape (K, T, M)
    
    # Adjust temporal dimensions for possible STFT truncation
    min_T = min(M_1.shape[1], X_stft.shape[1])
    M_1, M_2 = M_1[:, :min_T], M_2[:, :min_T]
    X_stft = X_stft[:, :min_T, :]

    # 3. Compute Target Steering Vector (130 degrees based on source_pos_2d)
    K, T, M_mics = X_stft.shape
    frecs = np.linspace(0, fs/2, K)
    sv_target = compute_rtf_steering_vector(frecs, source_pos_2d, mic_coords, ref_mic_idx=0, mode="near_field", squeeze=True)

    # 4. Spatial Judge decides the target permutation
    M_target, M_noise, target_raw_audio = spatial_permutation_judge(X_stft, M_1, M_2, sv_target, raw_1, raw_2)

    # 5. Apply MVDR using the winning mask
    print(" -> [MVDR] Applying Spatial Beamforming...")
    Y_stft = Neural_MVDR_recursive(X_stft, M_target, fs, mic_coords, source_pos_2d)
    
    # 6. Inverse STFT
    _, y_time = signal.istft(Y_stft, fs=fs, nperseg=length_fft, noverlap=length_fft - hop_length_fft)
    
    original_length = time_domain_input.shape[1]
    
    # Return both the MVDR output and the raw network target audio
    return y_time[:original_length], target_raw_audio[:original_length]

if __name__ == "__main__":
    # CRITICAL: Corrected sample rate back to 8000 Hz
    FS = 8000
    M1, M2 = 8, 1          
    M = M1 * M2
    speed_of_sound = 343.0 

    iSIR_dB = 0 
    
    print("=== INTEGRATION TEST: PIPELINE (FREE-FIELD, ROOM, WPE+ROOM) ===")
    
    output_folder = "tests/data/mvdr_neural_output"
    os.makedirs(output_folder, exist_ok=True)
    
    # Create logarithmic spacing for the microphone array
    max_length = 0.30
    if M > 1:
        base = 2.0
        indices = np.arange(M)
        x_norm = (base**indices - 1) / (base**(M - 1) - 1)
        x = x_norm * max_length
    else:
        x = np.array([0.0])

    mic_coords = np.column_stack([x, np.zeros(M), np.zeros(M)])
    array_center = np.array([1.25, 2.0, 1.25])
    mic_coords = mic_coords - np.mean(mic_coords, axis=0) + array_center
    
    r = 1.0 
    ang_target = np.deg2rad(130)
    ang_interf = np.deg2rad(50)
    
    source_pos = array_center + np.array([r * np.cos(ang_target), r * np.sin(ang_target), 0.0])
    interf_pos1 = array_center + np.array([r * np.cos(ang_interf), r * np.sin(ang_interf), 0.0])
    source_pos_2d = source_pos.reshape(1, 3)

    print(" -> Initializing acoustic scene...") 
    acoustic_scene = SimAcoustic(mic_coords, array_mismatch=0.0, duration=15, fs=FS)
    acoustic_scene.set_source("tools/data/signals/FA01_09.wav", gain=1, position=source_pos_2d)
    acoustic_scene.set_interference("tools/data/signals/p011_emo_anger_sentences.wav", gain=1, position=interf_pos1.reshape(1,3))

    MODEL_NAME = "mpariente/ConvTasNet_WHAM_sepclean"

    # -------------------------------------------------------------------
    # PHASE 1: FREE FIELD SIMULATION (Anechoic)
    # -------------------------------------------------------------------
    cache_ff_path = os.path.join(output_folder, "cache_free_field.npz")
    
    if os.path.exists(cache_ff_path):
        print("\n--- PHASE 1: LOADING FREE FIELD SIMULATION FROM CACHE ---")
        cache_data = np.load(cache_ff_path)
        free_field_input = cache_data['input']
        vad_oracle_ff = cache_data['vad']
    else:
        print("\n--- PHASE 1: COMPUTING FREE FIELD SIMULATION ---")
        free_field_input, vad_oracle_ff = acoustic_scene.free_field(iSIR_dB=iSIR_dB, normalize=True, mode="ideal", VAD=True)
        np.savez(cache_ff_path, input=free_field_input, vad=vad_oracle_ff)
        
    save_wav("1_FF_input_mix_mic0.wav", FS, free_field_input[0], output_folder)

    print(" -> Applying Recursive MVDR...")
    output_ff, raw_net_ff = apply_neural_mvdr_bridge(free_field_input, mic_coords, source_pos_2d, FS, MODEL_NAME)
    
    save_wav("2_FF_output_final.wav", FS, normalize_signal(output_ff), output_folder)
    save_wav("2_FF_RAW_NETWORK_mic0.wav", FS, normalize_signal(raw_net_ff), output_folder)

    # -------------------------------------------------------------------
    # PHASE 2: ROOM SIMULATION (Reverberant)
    # -------------------------------------------------------------------
    cache_room_path = os.path.join(output_folder, "cache_room.npz")
    
    if os.path.exists(cache_room_path):
        print("\n--- PHASE 2: LOADING ROOM SIMULATION FROM CACHE ---")
        cache_data = np.load(cache_room_path)
        room_input = cache_data['input']
        vad_oracle_room = cache_data['vad']
    else:
        print("\n--- PHASE 2: COMPUTING ROOM SIMULATION ---")
        room_dimensions = np.array([4.0, 5.0, 2.5])
        room_sim_dic = acoustic_scene.get_eval_scene(
            room_dimensions=room_dimensions, desire_RT=0.5, iSIR_dB=iSIR_dB, mode="ideal"
        )
        room_input = room_sim_dic["mic_signals"]
        vad_oracle_room = room_sim_dic["VAD"]
        np.savez(cache_room_path, input=room_input, vad=vad_oracle_room)
    
    save_wav("3_ROOM_input_mix_mic0.wav", FS, room_input[0], output_folder)

    print(" -> Applying Recursive MVDR (Without WPE)...")
    output_rm, raw_net_rm = apply_neural_mvdr_bridge(room_input, mic_coords, source_pos_2d, FS, MODEL_NAME)
    
    save_wav("4_ROOM_output_final.wav", FS, normalize_signal(output_rm), output_folder)
    save_wav("4_ROOM_RAW_NETWORK_mic0.wav", FS, normalize_signal(raw_net_rm), output_folder)

    # -------------------------------------------------------------------
    # PHASE 3: WPE + MVDR PIPELINE
    # -------------------------------------------------------------------
    print("\n--- PHASE 3: WPE + MVDR PIPELINE ---")
    print(" -> Applying Online WPE Dereverberation on Room Simulation...")
    
    wpe_output = process_wpe_online(room_input, delay=1, taps=12)
    
    save_wav("5_WPE_input_mix_mic0.wav", FS, wpe_output[0], output_folder)

    print(" -> Applying Recursive MVDR on Dereverberated Signals...")
    output_wpe, raw_net_wpe = apply_neural_mvdr_bridge(wpe_output, mic_coords, source_pos_2d, FS, MODEL_NAME)
    
    # BUG FIXED: Saving the correct variable for the raw network output
    save_wav("6_WPE_ROOM_RAW_NETWORK_mic0.wav", FS, normalize_signal(raw_net_wpe), output_folder)
    save_wav("6_WPE_ROOM_output_final.wav", FS, normalize_signal(output_wpe), output_folder)

    print("\n -> Pipeline completed successfully.")